require 'settings'
require 'plugins'

require 'plugin_settings.autocompletion'
require 'plugin_settings.lspconfig'
require 'plugin_settings.nullls'
require 'plugin_settings.tree'
require 'plugin_settings.symbolsoutline'
require 'plugin_settings.catppuccin'
require 'plugin_settings.lualine'
require 'plugin_settings.bufferline'
require 'plugin_settings.autopairs'
require 'plugin_settings.gitsigns'
require 'plugin_settings.treesitter'
require 'plugin_settings.telescope'
require 'plugin_settings.trouble'
require 'plugin_settings.neogen'
require 'plugin_settings.startify'
